name: Release

on:
  push:
    tags:
      - 'v*' # will trigger the release workflow for any tag starting with v

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.3"
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Build Project
        run: make build

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --parallelism 1 --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
